version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: srm
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: openSRM
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  data:
    driver: local
